#
# Copyright (c) 2024 Lucas Dietrich <ld.adecy@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

# Debug
# CONFIG_OUTPUT_DISASSEMBLY=y
# CONFIG_OUTPUT_SYMBOLS=y
# CONFIG_OUTPUT_STAT=y

CONFIG_KERNEL_BIN_NAME="teal"
CONFIG_DEBUG=y

# MCUBOOT features
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_IMG_BLOCK_BUF_SIZE=512
CONFIG_IMG_ENABLE_IMAGE_CHECK=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y

# usb (TODO move to dedicated board config)
CONFIG_USB_CDC_ACM=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_COMPOSITE_DEVICE=y
CONFIG_USB_DFU_CLASS=y

# We need to disable the logs in the USB CDC ACM driver otherwise 
# the logs will be printed on the (USB) console causing a chain reaction 
# (eventually recursion leading to a stack overflow)
CONFIG_USB_CDC_ACM_LOG_LEVEL_ERR=y

# usb info
CONFIG_USB_DEVICE_MANUFACTURER="Lucas"
CONFIG_USB_DEVICE_PRODUCT="Teal CANIoT"

# st microelectronics
CONFIG_USB_DEVICE_VID=0x0483
CONFIG_USB_DEVICE_PID=0xFFFF

CONFIG_CANIOT_LIB=y
CONFIG_CANIOT_DEVICE_DRIVERS_API=y

# Application specific configurations
CONFIG_APP_USB_DFU_FW_DOWNLOAD=y