#
# Copyright (c) 2024 Lucas Dietrich <ld.adecy@gmail.com>
#
# SPDX-License-Identifier: Apache-2.0
#

# Debug
# CONFIG_OUTPUT_DISASSEMBLY=y
# CONFIG_OUTPUT_SYMBOLS=y
# CONFIG_OUTPUT_STAT=y

CONFIG_KERNEL_BIN_NAME="teal"
CONFIG_DEBUG=y

CONFIG_LOG=y

CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_MAIN_STACK_SIZE=4096

CONFIG_RUST=y
CONFIG_RUST_ALLOC=y

CONFIG_TEST=y
CONFIG_STM32L4_MCO=y