manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: lucasdietrich
      url-base: https://github.com/lucasdietrich
  projects:
    - name: zephyr-lang-rust
      path: modules/lang/rust
      remote: lucasdietrich
      revision: can
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.1.0
      import: true
  self:
    path: teal-caniot-device